### ISSUE TITLE
Not works on 1.16.5

### ISSUE THREAD

**Issue by Switch-Back18** [xMGZx/UnifyTags#12] opened 2022-07-22 20:51 UTC
Hello the script not works on 1.16.5

Here is my logs

SERVER : https://www.toptal.com/developers/hastebin/ejuxuwoveg.yaml

Can you fix it ?

Thanks for advice ^^

**Comment by jimmon89** [comment] 2022-07-24 19:38
Seems like a duplicate of #10 
Possibly also #11 
The error about copper is the same as issue 10
And the errors about immersive petroleum could be issue 11

**Comment by mathgeniuszach** [comment] 2022-07-24 19:45
Please use the most up-to-date version of rhino and of UnifyTags; it's written at the top of the curseforge page in BRIGHT RED LETTERS. If the error persists with those scripts, feel free to reopen.

**Comment by Switch-Back18** [comment] 2022-07-24 20:09
I use the latest version of Rhino ( rhino-forge-1605.1.5-build.75 ) and latest version of Unify Tags (UnifyTags-1.12) .

All is up to date.

**Comment by jimmon89** [comment] 2022-07-24 20:14
the version of UnifyTags on curse (1.12) is not the newest
the newest is found here on github
here's a direct link if you don't know how to download the latest master from here
https://codeload.github.com/xMGZx/UnifyTags/zip/refs/heads/main

**Comment by mathgeniuszach** [comment] 2022-07-24 20:25
The Object.entries() error in there is still persistent I see though. Such is a vanilla javascript feature, but I suppose Rhino doesn't support it in the 1.16 version when converting between Java and javascript types. Will fix.

**Comment by mathgeniuszach** [comment] 2022-07-24 21:13
mmmmmmm the name of the function went from `gatherAllItemIDs()` to `getAllItemIds` to `getObjectIds`, and in 1.16 that function is private, meaning I can't use it. I'll just disable tag intersections on 1.16, which should fix the problem.

**Comment by mathgeniuszach** [comment] 2022-07-24 21:34
Fixed by https://github.com/xMGZx/UnifyTags/commit/7d239870755074cab2da952e18c50d5d7275634d

**Closed as completed by mathgeniuszach** 2022-07-24 21:34 UTC
