### ISSUE TITLE
script is unifying tags like "forge:ingots" into only one type when they should be all ingots

### ISSUE THREAD

**Issue by ProGoofster** [xMGZx/UnifyTags#21] opened 2023-03-25 17:43 UTC
1.18, noticed this issue with tinker's construct casting plates, although kubejs and tcon is kinda finnicky so you might be able to see this better on a different mod

**Comment by mathgeniuszach** [comment] 2023-03-26 21:29
Can you be a bit more specific, and provide something like a video or images? The #forge:ingots tag is not unified by default, only subtags of it are.

**Comment by mathgeniuszach** [comment] 2023-03-26 21:32
UnifyTags by design unifies all the items in a tag. You can edit what tags UnifyTags chooses to unify in the script itself, and add your own. This is base functionality of the script.

**Comment by mathgeniuszach** [comment] 2023-05-01 01:10
I'm going to close this issue as I have no way of knowing if there's an issue here or if you're just using the script incorrectly. If you can provide more information on this issue in the future, feel free to reopen this.

**Closed as completed by mathgeniuszach** 2023-05-01 01:10 UTC
